volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
      - ./sql/create_tables_postgres.sql:/docker-entrypoint-initdb.d/create_tables_postgres.sql

  finanblue:
    image: finanblue
    build:
      context: .
    ports:
      - "20000:80"